SELECT O.PRODUCT_ID, P.PRODUCT_NAME, SUM(O.AMOUNT * P.PRICE) TOTAL_SALES
FROM FOOD_ORDER O
JOIN FOOD_PRODUCT P ON (O.PRODUCT_ID = P.PRODUCT_ID)
WHERE TO_CHAR(O.PRODUCE_DATE, 'YYYYMM') = '202205'
GROUP BY O.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, O.PRODUCT_ID ASC