-- SELECT F.FLAVOR, SUM(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) TOTAL_ORDER, RANK() OVER(ORDER BY SUM(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) DESC) RANK
-- FROM FIRST_HALF F
-- JOIN JULY J ON (J.FLAVOR = F.FLAVOR)
-- GROUP BY F.FLAVOR, J.FLAVOR;

SELECT FLAVOR
FROM (SELECT F.FLAVOR, SUM(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) TOTAL_ORDER, RANK() OVER(ORDER BY SUM(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) DESC) RANK
FROM FIRST_HALF F
JOIN JULY J ON (J.FLAVOR = F.FLAVOR)
GROUP BY F.FLAVOR, J.FLAVOR)
WHERE RANK <= 3;
