SELECT B.TITLE TITLE, B.BOARD_ID BOARD_ID, R.REPLY_ID REPLY_ID, R.WRITER_ID WRITER_ID, R.CONTENTS CONTENTS, TO_CHAR(R.CREATED_DATE, 'YYYY-MM-DD') CREATED_DATE
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_REPLY R ON (B.BOARD_ID = R.BOARD_ID)
WHERE TO_CHAR(B.CREATED_DATE, 'YYYYMM') LIKE '202210'
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;